<?php

namespace Tests\Services;

use Gvera\Helpers\config\Config;
use Gvera\Services\TwigService;
use PHPUnit\Framework\TestCase;

class TwigServiceTest extends TestCase
{

    private $service;

    public function setUp():void
    {
        $this->service = new TwigService($this->getMockedConfig());
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function testNeedsTwig()
    {

        $needsTwig = $this->service->needsTwig('Test', 'index', __DIR__ . '/../Views/');
        $this->assertTrue($needsTwig);
        $this->service->reset();
        $doesntNeedTwig = $this->service->needsTwig('Test', 'index');
        $this->assertFalse($doesntNeedTwig);
    }

    /**
     * @test
     */
    public function testLoadTwig()
    {
        $env = $this->service->loadTwig(__DIR__ . '/../Views/');
        $this->assertNotNull($env);
    }

    /**
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     * @test
     */
    public function testRender()
    {
        $this->service->reset();
        $this->service->loadTwig(__DIR__ . '/../Views/');
        $this->assertTrue($this->service->render('Test', 'index', []) === 'asd');
    }

    private function getMockedConfig()
    {
        $config = new \Gvera\Helpers\config\Config();
        return $config;
    }
}